# Generated by Django 5.2.1 on 2026-02-26 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                        ],
                        max_length=10,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Code interne",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de la matière"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("credits", models.IntegerField(default=0, verbose_name="Crédits")),
                (
                    "coefficient",
                    models.FloatField(default=1.0, verbose_name="Coefficient"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["semester__level__order", "semester__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la spécialité"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
                "ordering": ["university__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Titre du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/", verbose_name="Fichier"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("ppt", "PowerPoint"),
                            ("doc", "Word"),
                            ("video", "Vidéo"),
                            ("other", "Autre"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="python_project.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du semestre"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="Code (S1, S2, etc.)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="python_project.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Semestres",
                "ordering": ["level__order", "order"],
            },
        ),
        migrations.AddField(
            model_name="matiere",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="python_project.semester",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="python_project.speciality",
            ),
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'université"
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Logo URL"
                    ),
                ),
                (
                    "calendar_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Calendrier URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Université",
                "verbose_name_plural": "Universités",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="python_proj_name_0b7f91_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="speciality",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialities",
                to="python_project.university",
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(default=False, verbose_name="Alerte globale"),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID Utilisateur cible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="python_project.level",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="python_project.speciality",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="python_project.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID Firebase User"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, null=True, verbose_name="Photo URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="python_project.level",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="python_project.speciality",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="python_project.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="UserUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="ID Firebase User"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_universities",
                        to="python_project.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur Université",
                "verbose_name_plural": "Utilisateurs Universités",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="ID Firebase User"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lue")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="python_project.alert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statut de lecture",
                "verbose_name_plural": "Statuts de lecture",
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_read"],
                        name="python_proj_user_id_dfcfae_idx",
                    )
                ],
                "unique_together": {("alert", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="ID Firebase User"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="python_project.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document favori",
                "verbose_name_plural": "Documents favoris",
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="python_proj_user_id_eec8e6_idx",
                    )
                ],
                "unique_together": {("user_id", "document")},
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["matiere", "-created_at"], name="python_proj_matiere_2d0c06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_type"], name="python_proj_file_ty_b3c360_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_published"], name="python_proj_is_publ_297de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["level", "order"], name="python_proj_level_i_c08679_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("level", "code")},
        ),
        migrations.AddIndex(
            model_name="matiere",
            index=models.Index(
                fields=["semester", "name"], name="python_proj_semeste_079e95_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matiere",
            unique_together={("semester", "name")},
        ),
        migrations.AddIndex(
            model_name="level",
            index=models.Index(
                fields=["speciality", "order"], name="python_proj_special_3ab65b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="level",
            unique_together={("speciality", "name")},
        ),
        migrations.AddIndex(
            model_name="speciality",
            index=models.Index(
                fields=["university", "name"], name="python_proj_univers_13f032_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="speciality",
            unique_together={("university", "name")},
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["-created_at"], name="python_proj_created_688d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["user_id", "-created_at"], name="python_proj_user_id_2a844c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["is_global"], name="python_proj_is_glob_51660e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["user_id"], name="python_proj_user_id_3ce09d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useruniversity",
            index=models.Index(
                fields=["user_id"], name="python_proj_user_id_36145d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useruniversity",
            index=models.Index(
                fields=["university"], name="python_proj_univers_41e96f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useruniversity",
            unique_together={("user_id", "university")},
        ),
    ]
