# Generated by Django 5.2.1 on 2026-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CM", "Cours Magistral"),
                    ("TD", "Travaux Dirigés"),
                    ("TP", "Travaux Pratiques"),
                    ("EXAM", "Examen"),
                    ("PROJET", "Projet"),
                    ("AUTRE", "Autre"),
                ],
                default="CM",
                max_length=10,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="ID Utilisateur cible",
            ),
        ),
        migrations.AlterField(
            model_name="alertreadstatus",
            name="user_id",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="ID Firebase User"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("ppt", "PowerPoint"),
                    ("doc", "Word"),
                    ("video", "Vidéo"),
                    ("other", "Autre"),
                ],
                default="pdf",
                max_length=20,
                verbose_name="Type de fichier",
            ),
        ),
        migrations.AlterField(
            model_name="favoritedocument",
            name="user_id",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="ID Firebase User"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_id",
            field=models.CharField(
                db_index=True,
                max_length=255,
                unique=True,
                verbose_name="ID Firebase User",
            ),
        ),
        migrations.AlterField(
            model_name="useruniversity",
            name="user_id",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="ID Firebase User"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="python_proj_documen_e44b34_idx"
            ),
        ),
    ]
