# Generated by Django 5.2.1 on 2026-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0002_document_document_type_alter_alert_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
