# Generated by Django 5.2.1 on 2026-02-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0009_alter_alert_options_alter_document_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="python_project.university",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User universities",
                "unique_together": {("user_id", "university")},
            },
        ),
    ]
